// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKeetDashboard.API.Data;

#nullable disable

namespace PKeetDashboard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250311180000_CallSessionMessagesTable")]
    partial class CallSessionMessagesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PKeetDashboard.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.PromoBanner", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Text").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("CtaText").HasColumnType("nvarchar(max)");
                    b.Property<string>("CtaUrl").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("PromoBanners");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.SiteStat", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Key").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Value").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("Key").IsUnique();
                    b.ToTable("SiteStats");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.FeaturedCompany", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("LogoUrl").HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("FeaturedCompanies");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.FeatureCard", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("SectionKey").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ButtonText").HasColumnType("nvarchar(max)");
                    b.Property<string>("ButtonUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("IconName").HasColumnType("nvarchar(max)");
                    b.Property<string>("ImageUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("ExtraData").HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("FeatureCards");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.Testimonial", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Company").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Quote").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ProfileImageUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("VideoUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("TwitterUrl").HasColumnType("nvarchar(max)");
                    b.Property<string>("LinkedInUrl").HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("IconUrl").HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Topics");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.PricingPlan", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<decimal>("MonthlyPrice").HasColumnType("decimal(10,2)");
                    b.Property<decimal?>("YearlyPrice").HasColumnType("decimal(10,2)");
                    b.Property<int?>("YearlyDiscountPercent").HasColumnType("int");
                    b.Property<bool>("IsHighlighted").HasColumnType("bit");
                    b.Property<string>("ButtonText").HasColumnType("nvarchar(max)");
                    b.Property<string>("ButtonUrl").HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("PricingPlans");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.PlanFeature", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("PlanId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Text").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("PlanId");
                    b.ToTable("PlanFeatures");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.PlanFeature", b =>
                {
                    b.HasOne("PKeetDashboard.API.Entities.PricingPlan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.PricingPlan", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.Role", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Slug").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Url").HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.FooterLink", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Category").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Label").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Url").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("FooterLinks");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.SocialLink", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Platform").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Url").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("SocialLinks");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.NewsletterSubscription", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
                    b.Property<DateTime>("SubscribedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Email");
                    b.ToTable("NewsletterSubscriptions");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.LandingContent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Key").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Value").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("Key").IsUnique();
                    b.ToTable("LandingContents");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.CallSession", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("AiModel").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<int>("AiUsage").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").IsRequired().HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                    b.Property<string>("ExtraContext").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<DateTime?>("EndsAt").HasColumnType("datetime2");
                    b.Property<bool>("IsFreeSession").HasColumnType("bit");
                    b.Property<string>("Language").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<Guid?>("ResumeId").HasColumnType("uniqueidentifier");
                    b.Property<bool>("SaveTranscript").HasColumnType("bit");
                    b.Property<bool>("SimpleLanguage").HasColumnType("bit");
                    b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("CallSessions");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.CallSessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.HasIndex("CallSessionId");
                    b.ToTable("CallSessionMessages");
                });

            modelBuilder.Entity("PKeetDashboard.API.Entities.CallSessionMessage", b =>
                {
                    b.HasOne("PKeetDashboard.API.Entities.CallSession", null)
                        .WithMany()
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
